import Head from "next/head";
import styles from "../styles/Home.module.css";

import Link from "next/dist/client/link";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-screen flex items-center justify-center flex-col">
        <h1 className="text-6xl text-purple-600  font-bold">
          Clerk is Awesome
        </h1>
        <Link href={"/view"}>
          <a>
            <button className="bg-purple-600 text-white font-bold py-2 px-4 mt-4 hover:bg-purple-800 transition-all">
              View Profile
            </button>
          </a>
        </Link>
      </div>
      <div></div>
    </div>
  );
};

export default Home;
