import NavbarSignIn from "@/components/navbarsignin/navbarSignIn";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TProvider } from "@/components/toast";
import ContactBar from "@/components/contacbar/contactbar";
import {
  ClerkProvider,
  RedirectToSignIn,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";
import { useUser } from "@clerk/clerk-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const { isSignedIn, user, isLoaded } = useUser();

  // if (!isLoaded) {
  //   return null;
  // }

  return (
    <ClerkProvider>
      <html lang="en">
        <body className="light">
          <TProvider />
          <NavbarSignIn />
          {children}
          <ContactBar />
        </body>
      </html>
    </ClerkProvider>
  );
}
