import Navbar from "@/components/navbar/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TProvider } from "@/components/toast";
import ContactBar from "@/components/contacbar/contactbar";
import {
  ClerkProvider,
  RedirectToSignIn,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const publicPages = ["/"];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const pathname = usePathname();
  // const isPublic = publicPages.includes(pathname);

  return (
    <ClerkProvider>
      <html lang="en">
        <body className="light">
          {/* {isPublic ? (
            <>
              <Navbar />
              {children}
              <ContactBar />
            </>
          ) : (
            <>
              <SignedIn> */}
          <TProvider />
          <Navbar />
          {children}
          <ContactBar />
          {/* </SignedIn>
              <SignedOut>
                <RedirectToSignIn />
              </SignedOut>
            </>
          )} */}
        </body>
      </html>
    </ClerkProvider>
  );
}
